spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///security?serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: org.sang.model
