my:
  name: 江南一点雨
  address: China
  favorites:
    - 足球
    - 徒步
    - Coding

mys:
  userList:
    - name: 江南一点雨
      address: China
      favorites:
        - 足球
        - 徒步
        - Coding
    - name: sang
      address: GZ
      favorites:
        - 阅读
        - 吉他
