#服务器端口
server:
  port: 8001

spring:
  #服务名
  application:
    name: sevice-edu
  #环境设置：dev、test、prod
  profiles:
    active: dev
  #mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///oneline_education?serverTimezone=GMT%2B8
    username: root
    password: root
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

