spring:
  redis:
    database: 0   #redis数据库索引，redis提供了16个database。编号0-15
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8  #Redis连接池的最大连接数
        max-idle: 8    #最大空闲连接数
        #max-wait: -1ms #最大阻塞等待时间，默认-1.表示没有限制
        min-idle: 0    #最小空闲连接数
    password:         #默认密码为空时也要配置这一项，否则SocketTimeoutException
#   若用lettuce 配置和上面是类似的。如：
#   lettuce:
#     pool:
#        max-active: 8
